import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const viewport=document.querySelector('#viewport'),scoreEl=document.querySelector('#score'),ammoEl=document.querySelector('#ammo'),windEl=document.querySelector('#wind'),overlay=document.querySelector('#overlay'),statusEl=document.querySelector('#status'),helpEl=document.querySelector('#help'),cameraBtn=document.querySelector('#camera'),powerBar=document.querySelector('#power i');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);scene.fog=new THREE.Fog(0x071018,25,95);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(62,1,.1,130);let cameraMode=0,playing=false,charging=false,charge=0,score=0,ammo=10,wind=0,last=performance.now(),arrow=null,targetDir=1;
scene.add(new THREE.HemisphereLight(0xbdefff,0x132013,2));const sun=new THREE.DirectionalLight(0xffe4ad,3);sun.position.set(-8,15,8);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,140),new THREE.MeshStandardMaterial({color:0x14261f,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.z=-45;ground.receiveShadow=true;scene.add(ground);
for(let i=0;i<28;i++){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18,.28,4,6),new THREE.MeshStandardMaterial({color:0x33271d}));trunk.position.set((i%2?1:-1)*(7+Math.random()*18),2,-Math.random()*90);scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.8,5,7),new THREE.MeshStandardMaterial({color:0x17382b}));crown.position.copy(trunk.position).add(new THREE.Vector3(0,3,0));scene.add(crown)}
const target=new THREE.Group();target.position.set(0,3,-38);scene.add(target);const post=new THREE.Mesh(new THREE.BoxGeometry(.35,4,.35),new THREE.MeshStandardMaterial({color:0x6d4930}));post.position.y=-2.2;target.add(post);[['#eee8d5',2.6],['#20242a',2.05],['#52cbe0',1.52],['#ef554d',1.0],['#ffc857',.48]].forEach(([color,r],i)=>{const d=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.18,48),new THREE.MeshStandardMaterial({color,roughness:.75}));d.rotation.x=Math.PI/2;d.position.z=-i*.025;target.add(d)});
const player=new THREE.Group();scene.add(player);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.25,5,10),new THREE.MeshStandardMaterial({color:0x202d32}));body.position.y=1.35;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,16,12),new THREE.MeshStandardMaterial({color:0xb88964}));head.position.y=2.45;player.add(head);const bow=new THREE.Mesh(new THREE.TorusGeometry(.78,.045,8,28,Math.PI*1.45),new THREE.MeshStandardMaterial({color:0xffc857,emissive:0x6b3d00}));bow.rotation.z=-Math.PI*.72;bow.position.set(.45,1.75,-.3);player.add(bow);
const aim={x:0,y:0};function resize(){const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(viewport);
function setWind(){wind=(Math.random()*2-1)*2.2;windEl.textContent=`${Math.abs(wind).toFixed(1)} ${wind>=0?'→':'←'}`}
function reset(){score=0;ammo=10;arrow=null;playing=true;overlay.classList.add('hide');scoreEl.textContent='000';ammoEl.textContent='10';setWind()}
function toggleCamera(){cameraMode=1-cameraMode;cameraBtn.textContent=`CAMERA: ${cameraMode?'TPP':'FPP'}`}
function shoot(){if(!playing||!charging||arrow)return;charging=false;const power=25+charge*22;const dir=new THREE.Vector3(aim.x*.24,aim.y*.18,-1).normalize();const mesh=new THREE.Group();const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,1.5,8),new THREE.MeshStandardMaterial({color:0xf4ffff}));shaft.rotation.x=Math.PI/2;mesh.add(shaft);const tip=new THREE.Mesh(new THREE.ConeGeometry(.09,.28,8),new THREE.MeshStandardMaterial({color:0xffc857}));tip.rotation.x=-Math.PI/2;tip.position.z=-.88;mesh.add(tip);mesh.position.set(.35,1.75,-.8);scene.add(mesh);arrow={mesh,vel:dir.multiplyScalar(power)};ammo--;ammoEl.textContent=ammo;charge=0;powerBar.style.width='0%'}
function finishShot(hit,points=0){if(!arrow)return;scene.remove(arrow.mesh);arrow=null;if(hit){score+=points;scoreEl.textContent=String(score).padStart(3,'0');statusEl.textContent=points===50?'BULLSEYE!':`+${points}`;overlay.classList.remove('hide');setTimeout(()=>playing&&overlay.classList.add('hide'),500)}setWind();if(ammo<=0){playing=false;overlay.classList.remove('hide');statusEl.textContent='ROUND COMPLETE';helpEl.textContent=`SCORE ${score} · クリックで再挑戦`}}
function updateCamera(){if(cameraMode===0){camera.position.set(.25,1.85,.05);camera.lookAt(aim.x*8,2+aim.y*5,-35);player.visible=false}else{camera.position.lerp(new THREE.Vector3(4.8,3.4,7),.12);camera.lookAt(0,1.8,-15);player.visible=true}}
viewport.addEventListener('pointermove',e=>{const r=viewport.getBoundingClientRect();aim.x=THREE.MathUtils.clamp((e.clientX-r.left)/r.width*2-1,-.9,.9);aim.y=THREE.MathUtils.clamp(-(e.clientY-r.top)/r.height*2+1,-.75,.75)});viewport.addEventListener('pointerdown',()=>{if(!playing)return reset();if(!arrow){charging=true;charge=0}});addEventListener('pointerup',shoot);cameraBtn.onclick=toggleCamera;addEventListener('keydown',e=>{if(e.code==='KeyV')toggleCamera()});
function animate(now){const dt=Math.min((now-last)/1000,.04);last=now;target.position.x+=targetDir*3.2*dt;if(Math.abs(target.position.x)>5)targetDir*=-1;if(charging){charge=Math.min(1,charge+dt*.7);powerBar.style.width=`${charge*100}%`}if(arrow){arrow.vel.x+=wind*dt;arrow.vel.y-=6.5*dt;arrow.mesh.position.addScaledVector(arrow.vel,dt);arrow.mesh.lookAt(arrow.mesh.position.clone().add(arrow.vel));if(arrow.mesh.position.z<-37.7){const dx=arrow.mesh.position.x-target.position.x,dy=arrow.mesh.position.y-target.position.y,d=Math.hypot(dx,dy);finishShot(d<2.6,d<.48?50:d<1?25:d<1.52?10:d<2.05?5:2)}else if(arrow.mesh.position.y<0||arrow.mesh.position.z<-65)finishShot(false)}updateCamera();renderer.render(scene,camera);requestAnimationFrame(animate)}setWind();resize();requestAnimationFrame(animate);