import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const viewport=document.querySelector('#viewport'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),boostEl=document.querySelector('#boost'),overlay=document.querySelector('#overlay'),statusEl=document.querySelector('#status'),helpEl=document.querySelector('#help'),cameraBtn=document.querySelector('#camera');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07152a);scene.fog=new THREE.Fog(0x13213a,35,150);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));viewport.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(72,1,.1,190);scene.add(new THREE.HemisphereLight(0x9ad9ff,0x241022,2.4));const sun=new THREE.DirectionalLight(0xffd28a,3);sun.position.set(-12,20,8);scene.add(sun);
const world=new THREE.Group();scene.add(world);const roadMat=new THREE.MeshStandardMaterial({color:0x252d3a,roughness:.78}),edgeMats=[new THREE.MeshStandardMaterial({color:0xff5d61,emissive:0x441016}),new THREE.MeshStandardMaterial({color:0xf8f3d4})];
const track=[];for(let i=0;i<32;i++){const g=new THREE.Group(),road=new THREE.Mesh(new THREE.BoxGeometry(14,.35,8.3),roadMat);g.add(road);for(const side of[-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.55,.48,8.3),edgeMats[i%2]);rail.position.set(side*7.05,.32,0);g.add(rail)}for(const lane of[-2.35,2.35]){const mark=new THREE.Mesh(new THREE.BoxGeometry(.11,.03,3.6),new THREE.MeshBasicMaterial({color:0xe8f7ff}));mark.position.set(lane,.2,0);g.add(mark)}world.add(g);track.push(g)}
const decor=[];for(let i=0;i<44;i++){const g=new THREE.Group(),stem=new THREE.Mesh(new THREE.CylinderGeometry(.15,.28,2.2,6),new THREE.MeshStandardMaterial({color:0x493329})),top=new THREE.Mesh(i%3?new THREE.ConeGeometry(1.4,3.4,7):new THREE.SphereGeometry(1.2,10,8),new THREE.MeshStandardMaterial({color:i%3?0x1b5947:0xff6d8a,emissive:i%3?0x06150f:0x3b1019}));stem.position.y=1.1;top.position.y=3.1;g.add(stem,top);world.add(g);decor.push({mesh:g,s:i*18+12,side:i%2?1:-1})}
function makeCar(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.15,.65,3.7),new THREE.MeshStandardMaterial({color,metalness:.5,roughness:.28}));body.position.y=.7;g.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(1.55,.58,1.65),new THREE.MeshStandardMaterial({color:0x112033,metalness:.7}));roof.position.set(0,1.24,.05);g.add(roof);for(const px of[-1.04,1.04])for(const pz of[-1.15,1.15]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.2,10),new THREE.MeshStandardMaterial({color:0x070707}));wheel.rotation.z=Math.PI/2;wheel.position.set(px,.42,pz);g.add(wheel)}return g}
const player=makeCar(0xf6fbff);player.position.z=3;scene.add(player);const items=[];function itemMesh(type){if(type==='coin'){const m=new THREE.Mesh(new THREE.TorusGeometry(.38,.14,8,18),new THREE.MeshStandardMaterial({color:0xffd34e,emissive:0x6b3b00}));m.rotation.y=Math.PI/2;return m}if(type==='pad'){const m=new THREE.Mesh(new THREE.BoxGeometry(3.1,.12,4),new THREE.MeshStandardMaterial({color:0x37e6ff,emissive:0x126879}));return m}const g=new THREE.Group();for(const px of[-.65,.65]){const cone=new THREE.Mesh(new THREE.ConeGeometry(.38,1.15,8),new THREE.MeshStandardMaterial({color:0xff703d}));cone.position.set(px,.58,0);g.add(cone)}return g}
let best=+localStorage.nightRunBest||0,score=0,boost=100,mode='ready',cameraMode=1,last=performance.now(),distance=0,lateral=0,keys={},objects=[],flash=0;bestEl.textContent=String(best).padStart(4,'0');
const curve=s=>Math.sin(s*.018)*9+Math.sin(s*.006)*13,elev=s=>Math.sin(s*.013)*2.6+Math.max(0,Math.sin(s*.031))*1.8,slope=s=>(curve(s+1)-curve(s-1))*.5;
function placeAt(mesh,s,lane=0){const d=s-distance,base=curve(distance);mesh.position.set(curve(s)-base+lane,elev(s)-elev(distance),-d);mesh.rotation.y=-Math.atan(slope(s));mesh.rotation.z=-slope(s)*.035;return d}
function fillItems(){objects.forEach(o=>world.remove(o.mesh));objects=[];for(let i=1;i<30;i++){const s=distance+i*14+Math.random()*5,type=i%9===0?'pad':i%5===0?'cone':'coin',lane=[-4,0,4][Math.floor(Math.random()*3)],mesh=itemMesh(type);world.add(mesh);objects.push({mesh,s,type,lane,hit:false})}}
function resize(){const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(viewport);
function start(){score=0;boost=100;distance=0;lateral=0;mode='play';overlay.classList.add('hide');statusEl.textContent='START ENGINE';fillItems();last=performance.now()}
function toggleCamera(){cameraMode=1-cameraMode;cameraBtn.textContent=`CAMERA: ${cameraMode?'TPP':'FPP'}`}
function crash(){mode='dead';best=Math.max(best,Math.floor(score));localStorage.nightRunBest=best;bestEl.textContent=String(best).padStart(4,'0');overlay.classList.remove('hide');statusEl.textContent='WRECKED';helpEl.textContent=`DIST ${Math.floor(score)} · タップで再走`}
function bind(id,key){const el=document.querySelector(id);for(const type of['pointerdown','pointerup','pointercancel','pointerleave'])el.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();keys[key]=type==='pointerdown';if(type==='pointerdown'&&mode!=='play')start()})}bind('#left','left');bind('#right','right');bind('#boostBtn','boost');viewport.addEventListener('pointerdown',()=>{if(mode!=='play')start()});cameraBtn.onclick=e=>{e.stopPropagation();toggleCamera()};addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyV'&&!e.repeat)toggleCamera();if(mode!=='play'&&['Space','ArrowLeft','ArrowRight'].includes(e.code))start()});addEventListener('keyup',e=>keys[e.code]=0);
function updateWorld(now){const first=Math.floor(distance/8)*8;track.forEach((g,i)=>placeAt(g,first+i*8));decor.forEach((o,i)=>{while(o.s<distance-15)o.s+=792;placeAt(o.mesh,o.s,o.side*(11+(i%4)*2))});for(const o of objects){const d=placeAt(o.mesh,o.s,o.lane);o.mesh.visible=!o.hit&&d>-12&&d<260;if(o.type==='coin')o.mesh.rotation.y=now*.003;if(!o.hit&&d<4&&d>-2&&Math.abs(lateral-o.lane)<1.5){o.hit=true;if(o.type==='coin'){score+=35;boost=Math.min(100,boost+12);flash=.35}else if(o.type==='pad'){boost=Math.min(100,boost+40);flash=.7}else crash()}if(o.s<distance-12){o.s+=420;o.hit=false;o.lane=[-4,0,4][Math.floor(Math.random()*3)]}}}
function updateCamera(){const bank=-slope(distance)*.025;if(cameraMode===0){camera.position.lerp(new THREE.Vector3(lateral,.95,2.05),.35);camera.lookAt(lateral-slope(distance)*3,.6,-32);player.visible=false}else{camera.position.lerp(new THREE.Vector3(lateral*.45,4.8,10),.12);camera.lookAt(lateral-slope(distance)*3,.4,-24);player.visible=true}camera.rotation.z=THREE.MathUtils.lerp(camera.rotation.z,bank,.08)}
function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;if(mode==='play'){const boosting=(keys.Space||keys.boost)&&boost>0;if(boosting)boost-=31*dt;else boost=Math.min(100,boost+7*dt);const speed=30+Math.min(score/130,15)+(boosting?18:0),steer=((keys.ArrowLeft||keys.KeyA||keys.left)?-1:0)+((keys.ArrowRight||keys.KeyD||keys.right)?1:0);lateral=THREE.MathUtils.clamp(lateral+steer*8.5*dt,-5.5,5.5);player.position.x=THREE.MathUtils.lerp(player.position.x,lateral,.18);player.position.y=THREE.MathUtils.lerp(player.position.y,elev(distance+2)-elev(distance),.18);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,-steer*.2-slope(distance)*.04,.12);player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-steer*.12,.12);distance+=speed*dt;score+=speed*dt;flash=Math.max(0,flash-dt);scene.fog.color.setHex(flash?0x17475a:(Math.floor(distance/260)%2?0x231329:0x13213a));scoreEl.textContent=String(Math.floor(score)).padStart(4,'0');boostEl.textContent=`${Math.floor(boost)}%`;updateWorld(now)}updateCamera();renderer.render(scene,camera);requestAnimationFrame(loop)}fillItems();resize();updateWorld(0);requestAnimationFrame(loop);