import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),view=$('#viewport'),posEl=$('#position'),goalEl=$('#goal'),boostEl=$('#boost'),overlay=$('#overlay'),statusEl=$('#status'),helpEl=$('#help'),cameraBtn=$('#camera');
const FINISH=700,scene=new THREE.Scene();scene.background=new THREE.Color(0x07152a);scene.fog=new THREE.Fog(0x13213a,30,145);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));view.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(72,1,.1,180);scene.add(new THREE.HemisphereLight(0xa8ddff,0x281323,2.6));const sun=new THREE.DirectionalLight(0xffd28a,2.8);sun.position.set(-12,20,8);scene.add(sun);
const roadGeo=new THREE.BufferGeometry(),road=new THREE.Mesh(roadGeo,new THREE.MeshStandardMaterial({color:0x283140,roughness:.8,side:THREE.DoubleSide}));scene.add(road);const props=new THREE.Group();scene.add(props);const edgePieces=[],markPieces=[];
for(let i=0;i<44;i++){for(const side of[-1,1]){const m=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,5.1),new THREE.MeshStandardMaterial({color:i%2?0xff5d61:0xf5f1d4,emissive:i%2?0x441015:0x222015}));props.add(m);edgePieces.push({m,i,side})}for(const lane of[-2.3,2.3]){const m=new THREE.Mesh(new THREE.BoxGeometry(.1,.03,2.5),new THREE.MeshBasicMaterial({color:0xeaf8ff}));props.add(m);markPieces.push({m,i,lane})}}
const decor=[];for(let i=0;i<32;i++){const g=new THREE.Group(),stem=new THREE.Mesh(new THREE.CylinderGeometry(.15,.3,2.3,6),new THREE.MeshStandardMaterial({color:0x4a3328})),top=new THREE.Mesh(i%4?new THREE.ConeGeometry(1.5,3.6,7):new THREE.SphereGeometry(1.25,10,8),new THREE.MeshStandardMaterial({color:i%4?0x1b5942:0xff6586,emissive:i%4?0x06160e:0x3c101a}));stem.position.y=1.15;top.position.y=3.2;g.add(stem,top);props.add(g);decor.push({m:g,s:i*21+10,side:i%2?1:-1})}
function makeCar(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.15,.65,3.7),new THREE.MeshStandardMaterial({color,metalness:.55,roughness:.25}));body.position.y=.7;g.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(1.55,.58,1.65),new THREE.MeshStandardMaterial({color:0x112033,metalness:.7}));roof.position.set(0,1.24,.05);g.add(roof);return g}const player=makeCar(0xf7fbff);player.position.z=3;scene.add(player);
const finish=new THREE.Group(),banner=new THREE.Mesh(new THREE.BoxGeometry(14,.35,.35),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0x444444}));banner.position.y=5;finish.add(banner);for(const x of[-6.7,6.7]){const pole=new THREE.Mesh(new THREE.BoxGeometry(.35,5.2,.35),new THREE.MeshStandardMaterial({color:0xff5d61,emissive:0x441015}));pole.position.set(x,2.5,0);finish.add(pole)}for(let i=0;i<8;i++){const tile=new THREE.Mesh(new THREE.BoxGeometry(1.75,.04,1.5),new THREE.MeshBasicMaterial({color:i%2?0xffffff:0x101010}));tile.position.set(-6.1+i*1.75,.23,0);finish.add(tile)}scene.add(finish);
let distance=0,lateral=0,boostCharges=3,boostTime=0,slowTime=0,invincible=0,last=performance.now(),mode='ready',cameraMode=1,keys={},racers=[],rank=1,obstacles=[];const center=s=>Math.sin(s*.033)*18+Math.sin(s*.012)*10,height=s=>Math.sin(s*.021)*3+Math.max(0,Math.sin(s*.047))*2,heading=s=>Math.atan(center(s+.5)-center(s-.5));
function point(s,lane=0){const h0=heading(distance),hs=heading(s),dx=center(s)-center(distance)+lane*Math.cos(hs),dz=-(s-distance)+lane*Math.sin(hs),c=Math.cos(h0),n=Math.sin(h0);return new THREE.Vector3(dx*c+dz*n,height(s)-height(distance),-dx*n+dz*c)}function place(mesh,s,lane=0){const p=point(s,lane),yaw=heading(s)-heading(distance);mesh.position.copy(p);mesh.rotation.y=-yaw;mesh.rotation.z=-Math.sin(yaw)*.08;return p}
function roadUpdate(){const v=[],ix=[],steps=52,w=7;for(let i=0;i<=steps;i++){const s=distance-6+i*5,p=point(s),h=heading(s)-heading(distance),nx=Math.cos(h);v.push(p.x-w*nx,p.y,p.z,p.x+w*nx,p.y,p.z)}for(let i=0;i<steps;i++){const a=i*2;ix.push(a,a+2,a+1,a+1,a+2,a+3)}roadGeo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));roadGeo.setIndex(ix);roadGeo.computeVertexNormals();const base=Math.floor(distance/5)*5;edgePieces.forEach(o=>place(o.m,base+o.i*5,o.side*7.05));markPieces.forEach(o=>place(o.m,base+o.i*5,o.lane));decor.forEach((o,i)=>{while(o.s<distance-15)o.s+=672;place(o.m,o.s,o.side*(11+i%3*2))});place(finish,FINISH)}
function makeObstacle(type){const g=new THREE.Group();if(type==='barrier'){const bar=new THREE.Mesh(new THREE.BoxGeometry(3.4,1.05,.7),new THREE.MeshStandardMaterial({color:0xff5d61,emissive:0x441015}));bar.position.y=.7;g.add(bar);for(const x of[-1.25,0,1.25]){const stripe=new THREE.Mesh(new THREE.BoxGeometry(.45,1.1,.73),new THREE.MeshBasicMaterial({color:0xffffff}));stripe.position.set(x,.7,0);stripe.rotation.z=.35;g.add(stripe)}}else{const oil=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.5,.06,18),new THREE.MeshStandardMaterial({color:0x05080b,metalness:.8,roughness:.25}));oil.position.y=.2;g.add(oil)}return g}
function resetObstacles(){obstacles.forEach(o=>scene.remove(o.mesh));obstacles=[];const layout=[[85,-4,'barrier'],[125,0,'oil'],[170,4,'barrier'],[220,-4,'oil'],[265,0,'barrier'],[315,4,'oil'],[365,-4,'barrier'],[410,0,'oil'],[455,4,'barrier'],[505,-4,'oil'],[550,0,'barrier'],[595,4,'oil'],[640,-4,'barrier']];for(const [s,lane,type] of layout){const mesh=makeObstacle(type);scene.add(mesh);obstacles.push({mesh,s,lane,type,hit:false})}}
function resetRacers(){racers.forEach(r=>scene.remove(r.mesh));racers=[];const colors=[0x54f7ff,0xffc857,0xff5d61,0x9cff63,0xc079ff];for(let i=0;i<5;i++){const mesh=makeCar(colors[i]);scene.add(mesh);racers.push({mesh,s:-3-i*4,lane:[-4,0,4][i%3],target:[-4,0,4][i%3],speed:27.5+i*1.25+Math.random()*2,change:2+Math.random()*3,impact:0,finished:false})}}
function resize(){const r=view.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(view);function start(){distance=0;lateral=0;boostCharges=3;boostTime=0;slowTime=0;invincible=0;rank=1;mode='play';resetRacers();resetObstacles();overlay.classList.add('hide');last=performance.now()}function toggle(){cameraMode=1-cameraMode;cameraBtn.textContent=`視点: ${cameraMode?'三人称':'一人称'}`}
function finishRace(){if(mode!=='play')return;mode='finish';rank=1+racers.filter(r=>r.s>=FINISH).length;overlay.classList.remove('hide');statusEl.textContent=rank===1?'優勝！':`${rank}位`;helpEl.textContent='ゴール！ タップして再レース'}
function useBoost(){if(mode==='play'&&boostCharges>0&&boostTime<=0){boostCharges--;boostTime=1.35;invincible=Math.max(invincible,.45)}}function bind(id,key){const e=$(id);for(const t of['pointerdown','pointerup','pointercancel','pointerleave'])e.addEventListener(t,a=>{a.preventDefault();a.stopPropagation();keys[key]=t==='pointerdown';if(t==='pointerdown'&&mode!=='play')start();else if(t==='pointerdown'&&key==='boost')useBoost()})}bind('#left','left');bind('#right','right');bind('#boostBtn','boost');view.onpointerdown=()=>mode!=='play'&&start();cameraBtn.onclick=e=>{e.stopPropagation();toggle()};onkeydown=e=>{keys[e.code]=1;if(e.code==='Space'&&!e.repeat)useBoost();if(e.code==='KeyV'&&!e.repeat)toggle();if(mode!=='play'&&['Space','ArrowLeft','ArrowRight'].includes(e.code))start()};onkeyup=e=>keys[e.code]=0;
function updateNPC(dt){for(const r of racers){r.change-=dt;r.impact=Math.max(0,r.impact-dt);if(r.change<0){r.target=[-4,0,4][Math.floor(Math.random()*3)];r.change=2+Math.random()*4}r.lane=THREE.MathUtils.lerp(r.lane,r.target,dt*1.2);if(!r.finished){r.s+=r.speed*(r.impact>0?.72:1)*dt;if(r.s>=FINISH)r.finished=true}const p=place(r.mesh,r.s,r.lane);r.mesh.visible=p.z<18&&p.z>-145;if(r.impact<=0&&Math.abs(r.s-distance)<3.3&&Math.abs(r.lane-lateral)<1.8){r.impact=.8;r.s-=2.5;r.target=THREE.MathUtils.clamp(r.lane+(r.lane>=lateral?2.4:-2.4),-5.5,5.5)}}rank=1+racers.filter(r=>r.s>distance).length;posEl.textContent=`${rank}/6`}
function updateObstacles(dt){invincible=Math.max(0,invincible-dt);slowTime=Math.max(0,slowTime-dt);for(const o of obstacles){const p=place(o.mesh,o.s,o.lane);o.mesh.visible=!o.hit&&p.z<15&&p.z>-145;if(!o.hit&&Math.abs(o.s-distance)<3&&Math.abs(o.lane-lateral)<1.65){o.hit=true;if(invincible<=0){slowTime=o.type==='oil'?1.8:1.15;lateral=THREE.MathUtils.clamp(lateral+(lateral<=o.lane?-2.2:2.2),-5.5,5.5);player.rotation.z=o.type==='oil'?.45:-.3}}}}
function cameraUpdate(){if(cameraMode===0){camera.position.lerp(new THREE.Vector3(lateral,.95,2),.35);camera.lookAt(0,.3,-35);player.visible=false}else{camera.position.lerp(new THREE.Vector3(lateral*.4,4.8,10),.14);camera.lookAt(0,.2,-28);player.visible=true}}
function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;if(mode==='play'){boostTime=Math.max(0,boostTime-dt);const nitro=boostTime>0;const speed=(slowTime>0?18:29)+(nitro?19:0),steer=((keys.ArrowLeft||keys.KeyA||keys.left)?-1:0)+((keys.ArrowRight||keys.KeyD||keys.right)?1:0);lateral=THREE.MathUtils.clamp(lateral+steer*8.5*dt,-5.5,5.5);player.position.x=THREE.MathUtils.lerp(player.position.x,lateral,.18);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,-steer*.2,.12);player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-steer*.12,.12);distance+=speed*dt;updateNPC(dt);updateObstacles(dt);roadUpdate();goalEl.textContent=`${Math.max(0,Math.ceil(FINISH-distance))}m`;boostEl.textContent=`残り${boostCharges}回${boostTime>0?' 加速中':''}`;if(distance>=FINISH)finishRace()}cameraUpdate();renderer.render(scene,camera);requestAnimationFrame(loop)}resetRacers();resetObstacles();resize();roadUpdate();updateNPC(0);updateObstacles(0);requestAnimationFrame(loop);