import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),viewport=$('#viewport'),scoreEl=$('#score'),bestEl=$('#best'),boostEl=$('#boost'),overlay=$('#overlay'),statusEl=$('#status'),helpEl=$('#help'),cameraBtn=$('#camera');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07152a);scene.fog=new THREE.Fog(0x13213a,32,145);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));viewport.appendChild(renderer.domElement);const camera=new THREE.PerspectiveCamera(72,1,.1,180);scene.add(new THREE.HemisphereLight(0xa8ddff,0x281323,2.6));const sun=new THREE.DirectionalLight(0xffd28a,2.8);sun.position.set(-12,20,8);scene.add(sun);
const roadGeo=new THREE.BufferGeometry(),road=new THREE.Mesh(roadGeo,new THREE.MeshStandardMaterial({color:0x283140,roughness:.8,side:THREE.DoubleSide}));scene.add(road);const edges=new THREE.Group(),marks=new THREE.Group(),decor=new THREE.Group();scene.add(edges,marks,decor);const edgePieces=[],markPieces=[];
for(let i=0;i<44;i++){for(const side of[-1,1]){const m=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,5.1),new THREE.MeshStandardMaterial({color:i%2?0xff5d61:0xf5f1d4,emissive:i%2?0x441015:0x222015}));edges.add(m);edgePieces.push({m,i,side})}for(const lane of[-2.3,2.3]){const m=new THREE.Mesh(new THREE.BoxGeometry(.1,.03,2.5),new THREE.MeshBasicMaterial({color:0xeaf8ff}));marks.add(m);markPieces.push({m,i,lane})}}
for(let i=0;i<34;i++){const g=new THREE.Group(),stem=new THREE.Mesh(new THREE.CylinderGeometry(.15,.3,2.3,6),new THREE.MeshStandardMaterial({color:0x4a3328})),top=new THREE.Mesh(i%4?new THREE.ConeGeometry(1.5,3.6,7):new THREE.SphereGeometry(1.25,10,8),new THREE.MeshStandardMaterial({color:i%4?0x1b5942:0xff6586,emissive:i%4?0x06160e:0x3c101a}));stem.position.y=1.15;top.position.y=3.2;g.add(stem,top);decor.add(g);g.userData={s:i*19+8,side:i%2?1:-1}}
function car(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.15,.65,3.7),new THREE.MeshStandardMaterial({color,metalness:.55,roughness:.25}));body.position.y=.7;g.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(1.55,.58,1.65),new THREE.MeshStandardMaterial({color:0x112033,metalness:.7}));roof.position.set(0,1.24,.05);g.add(roof);return g}const player=car(0xf7fbff);player.position.z=3;scene.add(player);
let best=+localStorage.nightRunBest||0,score=0,boost=100,distance=0,lateral=0,last=performance.now(),mode='ready',cameraMode=1,keys={},objects=[];bestEl.textContent=String(best).padStart(4,'0');
const center=s=>Math.sin(s*.033)*18+Math.sin(s*.012)*10,height=s=>Math.sin(s*.021)*3+Math.max(0,Math.sin(s*.047))*2,heading=s=>Math.atan((center(s+.5)-center(s-.5)));
function localPoint(s,lane=0){const h0=heading(distance),hs=heading(s),dx=center(s)-center(distance)+lane*Math.cos(hs),dz=-(s-distance)+lane*Math.sin(hs),c=Math.cos(h0),n=Math.sin(h0);return new THREE.Vector3(dx*c+dz*n,height(s)-height(distance),-dx*n+dz*c)}
function place(mesh,s,lane=0){const p=localPoint(s,lane),yaw=heading(s)-heading(distance);mesh.position.copy(p);mesh.rotation.y=-yaw;mesh.rotation.z=-Math.sin(yaw)*.08;return p}
function rebuildRoad(){const positions=[],indices=[],steps=52,width=7;for(let i=0;i<=steps;i++){const s=distance-6+i*5,p=localPoint(s),h=heading(s)-heading(distance),nx=Math.cos(h);positions.push(p.x-width*nx,p.y,p.z,p.x+width*nx,p.y,p.z)}for(let i=0;i<steps;i++){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3)}roadGeo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));roadGeo.setIndex(indices);roadGeo.computeVertexNormals();const base=Math.floor(distance/5)*5;edgePieces.forEach(o=>place(o.m,base+o.i*5,o.side*7.05));markPieces.forEach(o=>place(o.m,base+o.i*5,o.lane));decor.children.forEach((m,i)=>{while(m.userData.s<distance-12)m.userData.s+=646;place(m,m.userData.s,m.userData.side*(11+i%3*2))})}
function item(type){if(type==='coin')return new THREE.Mesh(new THREE.TorusGeometry(.4,.14,8,18),new THREE.MeshStandardMaterial({color:0xffd34e,emissive:0x754300}));if(type==='pad')return new THREE.Mesh(new THREE.BoxGeometry(3,.12,4),new THREE.MeshStandardMaterial({color:0x39e9ff,emissive:0x126b7b}));const g=new THREE.Group();for(const x of[-.65,.65]){const m=new THREE.Mesh(new THREE.ConeGeometry(.38,1.2,8),new THREE.MeshStandardMaterial({color:0xff653b}));m.position.set(x,.6,0);g.add(m)}return g}
function fill(){objects.forEach(o=>scene.remove(o.mesh));objects=[];for(let i=1;i<28;i++){const type=i%10===0?'pad':i%6===0?'cone':'coin',mesh=item(type);scene.add(mesh);objects.push({mesh,type,s:i*15+Math.random()*5,lane:[-4,0,4][Math.floor(Math.random()*3)],hit:false})}}
function resize(){const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(viewport);
function start(){score=0;boost=100;distance=0;lateral=0;mode='play';overlay.classList.add('hide');fill();last=performance.now()}function toggle(){cameraMode=1-cameraMode;cameraBtn.textContent=`CAMERA: ${cameraMode?'TPP':'FPP'}`}function crash(){mode='dead';best=Math.max(best,Math.floor(score));localStorage.nightRunBest=best;bestEl.textContent=String(best).padStart(4,'0');overlay.classList.remove('hide');statusEl.textContent='WRECKED';helpEl.textContent=`DIST ${Math.floor(score)} · タップで再走`}
function bind(id,key){const el=$(id);for(const type of['pointerdown','pointerup','pointercancel','pointerleave'])el.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();keys[key]=type==='pointerdown';if(type==='pointerdown'&&mode!=='play')start()})}bind('#left','left');bind('#right','right');bind('#boostBtn','boost');viewport.onpointerdown=()=>mode!=='play'&&start();cameraBtn.onclick=e=>{e.stopPropagation();toggle()};onkeydown=e=>{keys[e.code]=1;if(e.code==='KeyV'&&!e.repeat)toggle();if(mode!=='play'&&['Space','ArrowLeft','ArrowRight'].includes(e.code))start()};onkeyup=e=>keys[e.code]=0;
function updateItems(now){for(const o of objects){const p=place(o.mesh,o.s,o.lane);o.mesh.visible=!o.hit&&p.z<12&&p.z>-145;if(o.type==='coin')o.mesh.rotation.y=now*.004;if(!o.hit&&p.z<5&&p.z>-2&&Math.abs(lateral-o.lane)<1.5){o.hit=true;if(o.type==='coin'){score+=35;boost=Math.min(100,boost+12)}else if(o.type==='pad')boost=Math.min(100,boost+42);else crash()}if(o.s<distance-10){o.s+=420;o.hit=false;o.lane=[-4,0,4][Math.floor(Math.random()*3)]}}}
function updateCamera(){if(cameraMode===0){camera.position.lerp(new THREE.Vector3(lateral,.95,2),.35);camera.lookAt(0,.3,-35);player.visible=false}else{camera.position.lerp(new THREE.Vector3(lateral*.4,4.8,10),.14);camera.lookAt(0,.2,-28);player.visible=true}}
function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;if(mode==='play'){const nitro=(keys.Space||keys.boost)&&boost>0;if(nitro)boost-=31*dt;else boost=Math.min(100,boost+7*dt);const speed=29+Math.min(score/150,14)+(nitro?19:0),steer=((keys.ArrowLeft||keys.KeyA||keys.left)?-1:0)+((keys.ArrowRight||keys.KeyD||keys.right)?1:0);lateral=THREE.MathUtils.clamp(lateral+steer*8.5*dt,-5.5,5.5);player.position.x=THREE.MathUtils.lerp(player.position.x,lateral,.18);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,-steer*.2,.12);player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-steer*.12,.12);distance+=speed*dt;score+=speed*dt;rebuildRoad();updateItems(now);scoreEl.textContent=String(Math.floor(score)).padStart(4,'0');boostEl.textContent=`${Math.floor(boost)}%`}updateCamera();renderer.render(scene,camera);requestAnimationFrame(loop)}fill();resize();rebuildRoad();updateItems(0);requestAnimationFrame(loop);